services:

  the-page-mongo:
    hostname: the-page-mongo
    image: mongo:5.0.28
    restart: always
    environment:
      MONGO_INITDB_DATABASE: the-page
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./mongo_data/db:/data/db
      - ./mongo_data/configdb:/data/configdb

  the-page-mongo-express:
    hostname: the-page-mongo-express
    depends_on:
      - the-page-mongo
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://the-page-mongo:27017/
      ME_CONFIG_MONGODB_SERVER: the-page-mongo
      ME_CONFIG_MONGODB_HOST: the-page-mongo
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_BASICAUTH_FILE: /run/secrets/me_config_basicauth
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/me_config_basicauth_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/me_config_basicauth_password
    secrets:
      - me_config_basicauth
      - me_config_basicauth_username
      - me_config_basicauth_password

  the-page-backend:
    hostname: the-page-backend
    depends_on:
      - the-page-mongo
    build:
      dockerfile: ./backend/dev.Dockerfile
    restart: always
    ports:
      - 3031:80
      - 9229:9229
    volumes:
      - ./backend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/mongo_uri
      JWT_SECRET_FILE: /run/secrets/backend_gwt_secret
      APP_BASE_PATH: /
      FRONTEND_BASE_URL: http://localhost:3032
    secrets:
      - backend_gwt_secret
      - mongo_uri

  the-page-frontend:
    hostname: the-page-frontend
    depends_on:
      - the-page-mongo
    build:
      dockerfile: ./frontend/dev.Dockerfile
    restart: always
    ports:
      - 3032:80
      - 9230:9229
    volumes:
      - ./frontend/src:/src
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/mongo_uri
      APP_BASE_HOSTNAME: thepage.local
    secrets:
      - mongo_uri

secrets:
  me_config_basicauth:
    file: me_config_basicauth.txt
  me_config_basicauth_username:
    file: me_config_basicauth_username.txt
  me_config_basicauth_password:
    file: me_config_basicauth_password.txt
  mongo_uri:
    file: mongo_uri.txt
  backend_gwt_secret:
    file: backend_gwt_secret.txt
