name: Build and Push Docker Image Manually

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'

      - name: Install dependencies for "backend" app
        run: npm install
        working-directory: ./backend/src

      - name: Install dependencies for "frontend" app
        run: npm install
        working-directory: ./frontend/src

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Git tag
        id: git_tag
        run: echo "::set-output name=TAG::$(git describe --tags --abbrev=0)"

      - name: Remove 'release/' prefix from tag
        id: version
        run: |
          TAG=${{ steps.git_tag.outputs.TAG }}
          VERSION=${TAG#release/}
          echo "::set-output name=VERSION::$VERSION"

      - name: Build and Push Docker image for backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/the-page-backend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/the-page-backend:${{ steps.version.outputs.VERSION }}
          file: ./backend/release.Dockerfile

      - name: Build and Push Docker image for frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/the-page-frontend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/the-page-frontend:${{ steps.version.outputs.VERSION }}
          file: ./frontend/release.Dockerfile

      - name: Logout from Docker Hub
        run: docker logout
